const doctorList = [
    {
        id: 1,
        image: 'https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/NemboLukni.png',
        name: 'Nembo Lukeni',
        education: 'MBBS. DMRD',
        designation: 'Senior Specialist',
        experience: '10+ years',
        link: '/doctor/detail/1',
        number: 123456789,
        department: 'General Medicine',
        email: 'Nembo@12gmail.com',
        gender: 'Male',
        time: '12:00 AM - 09:00 AM',
        workTime: '',
    },
    {
        id: 2,
        image: 'https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/MollieCobb.png',
        name: 'Mollie Cobb',
        education: 'MBBS. MD PAEDIATRICS',
        designation: 'Junior Specialist',
        experience: '2+ years',
        link: '/doctor/detail/2',
        number: 24564219,
        department: 'Neurology',
        email: 'Mollie@54gmail.com',
        gender: 'Female',
        time: '10:00 AM - 07:00 PM',
        workTime: '',
    },
    {
        id: 3,
        image: 'https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/YaraBarros.png',
        name: 'Yara Barros',
        education: 'MBBS. DNB (FAMILY)',
        designation: 'Senior Specialist',
        experience: '8+ years',
        link: '/doctor/detail/3',
        number: 7697964,
        department: 'Diabetology',
        email: 'Yara@504gmail.com',
        gender: 'Female',
        time: '06:00 PM - 03:00 AM',
        workTime: '',
    },
    {
        id: 4,
        image: 'https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/PaulWalker.png',
        name: 'Paul Walker',
        education: 'MBBS. MD (DERMATOLOGY)',
        designation: 'Senior Dermatology',
        experience: '5+ years',
        link: '/doctor/detail/4',
        number: 4598204756,
        department: 'Dermatology',
        email: 'Paul@212gmail.com',
        gender: 'Male',
        time: '12:00 AM - 09:00 AM',
        workTime: '',
    },
    {
        id: 5,
        image: 'https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/AmeliaEdwards.png',
        name: 'Amelia Edwards',
        education: 'MBBS. MD',
        designation: 'Senior Orthopedics',
        experience: '8+ years',
        link: '/doctor/detail/5',
        number: 47397655838,
        department: 'Orthopedics',
        email: 'Amelia@996gmail.com',
        gender: 'Female',
        time: '10:00 AM - 07:00 PM',
        workTime: '',
    },
    {
        id: 6,
        image: 'https://ej2.syncfusion.com/showcase/angular/appointmentplanner/assets/images/NoutGolstein.png',
        name: 'Nout Golstein',
        education: 'MS',
        designation: 'Senior Cardiologist',
        experience: '15+ years',
        link: '/doctor/detail/6',
        number: 256793446,
        department: 'Cardiology',
        email: 'Nout@04gmail.com',
        gender: 'Male',
        time: '06:00 PM - 03:00 AM',
        workTime: '',
    }
]

export default doctorList;